# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: UnitTests

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore source/3dPrintCalculatorLibrary.NUnitTest/3dPrintCalculatorLibrary.NUnitTest.csproj
    - name: Build
      run: dotnet build -c Release source/3dPrintCalculatorLibrary.NUnitTest/3dPrintCalculatorLibrary.NUnitTest.csproj
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal source/3dPrintCalculatorLibrary.NUnitTest/3dPrintCalculatorLibrary.NUnitTest.csproj
